name: "Trello Card Updater"
description: "Update Trello Card according to Pull Request's Status"
inputs:
  target-action-name:
    description: 'action name for trello operation'
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'


